package com.leetcode.mytest;

import java.util.HashMap;
import java.util.Map;

/**
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random
 * position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input: s = "abcd" t = "abcde"
 * 
 * Output: e
 * 
 * Explanation: 'e' is the letter that was added.
 *
 */
public class FindDifference {
	public char findTheDifference(String s, String t) {
		int slength = s.length();
		if (s.length() == 0) {
			return t.charAt(0);
		}
		char[] basic = "abcdefghigklnmopqrstuvwxyz".toCharArray();
		Map<Character,Boolean> map = new HashMap<>();
		for(char c: basic) {
			if (s.contains(new String("c"))) {
				
			}
		}
		
		char[] sChar = s.toCharArray();
		char[] tChar = t.toCharArray();
		for (int i = 0; i < slength; i++) {
			if (sChar[i] != tChar[i]) {
				return tChar[i];
			}
		}
		return tChar[slength];
	}
}
